" ### ### ### CONFIGURACIÓN VIM ### ### ###

"           GLOBAL
    filetype plugin indent on
    set number relativenumber
    set clipboard=unnamed
    " Fold
    set foldmethod=indent
    " Escapar
    inoremap jj <esc>
    " BUFFERS
    set hidden
    " Color 
    "    set background=dark
    syntax on
    colorscheme base16-3024
    let base16colorspace=256
    set termguicolors

"           INDENTACIÓN
    set shiftwidth=4
    set tabstop=4
    set expandtab
    set autoindent
    filetype indent on

"           CURSOR LINE
    set cursorline
    "    :highlight Cursorline cterm=bold ctermbg=black

"           BUSQUEDA
    " Resaltado
    set hlsearch
    " Desabilitar resaltado
    "    nnoremap :noh<return><esc>
    " Resaltar pares [] {} etc.
    set showmatch
    " sensibilidar
    set ignorecase
    set smartcase
    set incsearch

"           CONFIGURACION ATAJOS DE TECLADO
    " Tecla líder
    let mapleader = ","

    " Auto completar, cierre de pares
    inoremap ( ()<Esc>i
    inoremap (<CR> (<CR>)<Esc>O
    inoremap { {}<Esc>i
    inoremap {<CR> {<CR>}<Esc>O
    inoremap [ []<Esc>i
    inoremap [<CR> [<CR>]<Esc>O
    inoremap < <><Esc>i
    inoremap ' ''<Esc>i
    inoremap " ""<Esc>i

    " LLAMAR SHELL
    nnoremap - !!$SHELL<Enter>

    " LLAMAR DICCIONARIO ESPAÑOL
    nnoremap \ :setlocal spell! spelllang=es<Enter>

"           GUIAS
    inoremap ;g <++>
    inoremap <leader><leader> <Esc>/<++><Enter>"_c4l
    vnoremap <leader><leader> <Esc>/<++><Enter>"_c4l
    nnoremap <leader><leader> <Esc>/<++><Enter>"_c4l

"           PLANTILLAS
    " Comentario de cabezera
    nnoremap ,h :-1read $HOME/.vim/templates/head<CR>
    " HTML Bootstrap
    nnoremap ,bh :-1read $HOME/.vim/templates/html/bootstrap_sk.html<CR>
